# Generated by Django 5.1.1 on 2024-09-27 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BooksManagement', '0004_borrowedbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowedbook',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
